// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYvN7nfZw8tErauuUv2rb3EQsscCLDTLE',
    appId: '1:706057096800:web:c9142e7fe5c0c728e43d05',
    messagingSenderId: '706057096800',
    projectId: 'cp-movies',
    authDomain: 'cp-movies.firebaseapp.com',
    storageBucket: 'cp-movies.appspot.com',
    measurementId: 'G-CVL44R9WX4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9dMXzd_h5G_J-t3GpVqg7IltSkitupW0',
    appId: '1:706057096800:android:fa2d47ae73bec33ce43d05',
    messagingSenderId: '706057096800',
    projectId: 'cp-movies',
    storageBucket: 'cp-movies.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnww2Gi9Bi_N8IUNi_kQAYemzTxFuatUE',
    appId: '1:706057096800:ios:33dd131e819f244be43d05',
    messagingSenderId: '706057096800',
    projectId: 'cp-movies',
    storageBucket: 'cp-movies.appspot.com',
    iosBundleId: 'com.example.cpMovies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnww2Gi9Bi_N8IUNi_kQAYemzTxFuatUE',
    appId: '1:706057096800:ios:39212b34af0973ffe43d05',
    messagingSenderId: '706057096800',
    projectId: 'cp-movies',
    storageBucket: 'cp-movies.appspot.com',
    iosBundleId: 'com.example.cpMovies.RunnerTests',
  );
}
